services:

  darthvader:
    build: dnsserver
    hostname: darthvader
    networks:
      rededns:
        ipv4_address: 192.168.20.10
    volumes:
      - ./darthvader/named.conf.options:/etc/bind/named.conf.options
      - ./darthvader/named.conf.local:/etc/bind/named.conf.local
      - ./darthvader/zonas/db.starwars.lan:/etc/bind/db.starwars.lan
      - ./darthvader/zonas/db.192.168.20:/etc/bind/db.192.168.20

  mandalorian:
    build: dnsserver
    hostname: mandalorian
    networks:
      rededns:
        ipv4_address: 192.168.20.9
    volumes:
      - ./mandalorian/named.conf.options:/etc/bind/named.conf.options

  darthsidious:
    build: dnsserver
    hostname: darthsidious
    depends_on:
      - darthvader
      - mandalorian
    networks:
      rededns:
        ipv4_address: 192.168.20.11
    volumes:
      - ./darthsidious/named.conf.local:/etc/bind/named.conf.local

  cliente:
    build: cliente
    hostname: cliente1
    networks:
      rededns:
        ipv4_address: 192.168.20.110
    volumes:
      - ./cliente/rndc.conf:/etc/bind/rndc.conf
      - ./cliente/chave.key:/etc/bind/chave.key
      - ./cliente/actualiza.txt:/etc/bind/actualiza.txt
    dns:
      - 192.168.20.10
      - 192.168.20.9

networks:
  rededns:
    ipam:
      config:
        - subnet: 192.168.20.0/24
